### ISSUE TITLE
Noop for DEBUG builds

### ISSUE THREAD

**Issue by lmirosevic** [orta/ARAnalytics#186]
Hi @orta,

I usually don't want data from development builds polluting my analytics dashboards, so it would be nice if the library replaced the analytics providers' initialisation and event logging with a noop when DEBUG is defined.

I was thinking of adding a pair of class methods to ARAnalytics along the lines of:
```objc
/// When set to NO, ARAnalytics will not send out any data for builds that have the DEBUG flag defined. Defaults to YES.
+ (void)setAnalyticsEnabledForDebugBuilds:(BOOL)enabled;

/// Returns YES when analytics are enabled for DEBUG builds.
+ (BOOL)isAnalyticsEnabledForDebugBuilds;
```

The default for this setting would be YES for backwards compatibility reasons.

Would you accept a PR that adds this functionality?

**Comment by orta** [comment]
Hey @lmirosevic - so I've encountered production crashes before because developers are not running the actual code ( accidentally sending a `nil` into an NSDictionary for example )  that generates the analytics events. 

We tend to have code [like this](https://github.com/artsy/eigen/blob/master/Artsy/App/ARAppDelegate+Analytics.m#L62-L70) that checks for a bundle ID (or if it's in debug) then runs with a different identifier so that devs/beta tests don't end up in the same analytics buckets. Unless @Daniel1of1 has strong opinions on having it in, I'd probably fall in the "makes it easy to shoot yourself in the foot" camp, and say no.

**Comment by Daniel1of1** [comment]
I have no strong opinions on having it in. I feel it might be better implemented along the lines @orta mentions if one wishes to separate production / debug analytics , or have a `-setupAnalytics:(BOOL)enabled` of sorts which will start ARAnalytics or not (based on `DEBUG` defined or similar).

I'm sure I can be swayed but my initial impression is also "makes it easy to shoot yourself in the foot" camp :tent:

**Comment by orta** [comment]
:+1:
