### ISSUE TITLE
Other libs that provide a DSL that allows one shot mapping of analytic events to user inputs?

### ISSUE THREAD

**Issue by sirvon** [orta/ARAnalytics#208]
This technique using a DSL to allow you to blanket a controller with analytic calls in one place is superb!

Does the author or anyone else know other ios analytics libs that offer the same capabilities but using swift primarily?

And what about for Android?

Yes, there are tons of analytic service providers. But I have yet to come across this ability to map all the button clicks or gestures..swipes..etc in one class or controller.

How could this technique be administer and what is this pattern called, where you are hooking into globally into user inputs?

thanks for this lib!

**Comment by orta** [comment]
The pattern is called Aspects. You could use other [Aspect oriented Pods](https://cocoapods.org/?q=aspects). We opted for reactive cocoa because it was already in our app.

However if "not built in swift" is your issue, I think you're going to be disappointed. You can obviously use ARAnalytics in swift. The Aspects sort of thing requires runtime support that obj-c has, and swift aims to not have this feature. WRT Android, I have no idea there alas, I only do iOS.

**Comment by sirvon** [comment]
thanks for that knowledge! AOP!@#!
